-- Agentic Activities Table
-- Stores AI-generated wellness activities (breathing, workouts, meals)
-- Generated by NeuralSeek mAIstro based on schedule intensity and mood

CREATE TABLE IF NOT EXISTS agentic_activities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  activity_type VARCHAR(20) NOT NULL CHECK (activity_type IN ('BREATHING', 'WORKOUT', 'MEAL')),
  title TEXT NOT NULL,
  description TEXT,
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  duration_sec INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED')),
  
  -- Google Calendar sync (optional)
  calendar_event_id TEXT,
  synced_to_calendar BOOLEAN DEFAULT FALSE,
  
  -- Activity metadata
  schedule_intensity VARCHAR(10), -- Context: high/medium/low
  mood_score DECIMAL(3,1),        -- Context: mood when generated
  stress_level VARCHAR(10),       -- Context: stress when generated
  energy_level VARCHAR(10),       -- Context: energy when generated
  
  -- Generation info
  generated_by VARCHAR(50) DEFAULT 'maistro', -- maistro or fallback
  generation_reasoning TEXT,                  -- Why this activity was chosen
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  skipped_at TIMESTAMPTZ,
  
  -- User feedback
  user_rating INTEGER CHECK (user_rating >= 1 AND user_rating <= 5),
  user_feedback TEXT
);

-- Indexes for performance
CREATE INDEX idx_agentic_activities_user_id ON agentic_activities(user_id);
CREATE INDEX idx_agentic_activities_start_time ON agentic_activities(start_time);
CREATE INDEX idx_agentic_activities_status ON agentic_activities(status);
CREATE INDEX idx_agentic_activities_type ON agentic_activities(activity_type);
CREATE INDEX idx_agentic_activities_created_at ON agentic_activities(created_at);

-- Composite index for user's daily activities
CREATE INDEX idx_agentic_activities_user_date ON agentic_activities(user_id, start_time);

-- Comments
COMMENT ON TABLE agentic_activities IS 'AI-generated wellness activities from NeuralSeek mAIstro';
COMMENT ON COLUMN agentic_activities.activity_type IS 'BREATHING (meditation/calm), WORKOUT (movement/fitness), MEAL (nutrition)';
COMMENT ON COLUMN agentic_activities.schedule_intensity IS 'Schedule context when activity was generated';
COMMENT ON COLUMN agentic_activities.generated_by IS 'maistro (AI) or fallback (rule-based)';
COMMENT ON COLUMN agentic_activities.generation_reasoning IS 'AI explanation for why activity was recommended';
